spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lovers-space?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 701007
    driver-class-name: com.mysql.cj.jdbc.Driver
