spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loverspace?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog.xml
  quartz:
    job-store-type: memory

mybatis:
  mapper-locations: classpath:mapper/**/*.xml


schedule:
  everyDayImage: "* * * * * ? *"